apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-26-jenkins
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.4.0
    helm:
      valueFiles:
        - $values/jenkins/values.yaml
    chart: jenkins
  - repoURL: 'https://github.com/heinzdmx/argocd-katas'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-26
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
